@startuml

class Courses {
    String code 
    String short_description
    Int duration
    Date schedule
    Real price
}

class Registration {
    String name 
    String last_name 
    Int document 
    String work_activity
    String payment_method_type
}

class PaymentMethods {
    String name
    String type
}

class CardType {
    String type
    Int number
    Int security_code
    Date expiration
}

class Voucher {
    String course_information
    String payment_method_type
}

Courses *-- Registration
Registration o-- PaymentMethods
PaymentMethods o-- CardType
Voucher o-- CardType

@enduml