@startuml

class People {
    # name: string
    # last_name: string
    # dni: int
    # birth_date: date 
    # gender: string
    # nacionality: string
}

class Students {
    - fee_paid: real
}

class Teachers {
    - amount_hours: real
    - value: real
}

class Address {
    - street: string
    - number: string
    - floor: int
    - deparment: string 
    - location: string 
    - province: string 
    - country: string
}

class Subjects {
    - name: string
    - code: string 
    - type: string
    - correlatives: array
}

class Courses {
    - year: int
    - subject: Subjects
    - teacher: Teachers
    - students: Students
    - classroom: string
}

class StudentGrade {
    - grade: Grades
    - student: Students
}

class Grades {
    - grade: real 
    - type: string
    - typeGrade: string
}

People <|-- Students
People <|-- Teachers

People *-- Address

Subjects o-- Subjects

Courses o-- Subjects
Courses o-- Teachers

Courses *-- StudentGrade
StudentGrade *-- Grades
StudentGrade o-- Students


@enduml